### ISSUE TITLE
Implementing Multilingual Support (English & French)

### ISSUE THREAD

**Issue by pedrohbraga** [caressofsteel/hugo-story#57]
Hi, @caressofsteel !

Thank you so much for making this theme available! It has been very fun to create my academic website with it!

Bilingualism is culturally and professionally essential to where I live and to myself. Because of this, I have been trying to implement multilingual support for Canadian English and Canadian French into the theme you developed.

Despite following some insights from blogs and Hugo's documents on multilingual support, I'm encountering issues where only certain elements are displaying, and the language switch isn't functioning as expected.

I was wondering if you (or others) would have insights on what could be done here to identify and resolve the issues I am having:

## **What I've Tried So Far**

1. **Enabled Multilingual Mode in Configuration:**
   - Updated `hugo.toml` with multilingual settings.

2. **Structured Data Files for Each Language:**
   - Divided YAML data files into `data/en/` and `data/fr/` directories with appropriate translations.

3. **Modified `banner.html` for Language Switching:**
   - Added conditional logic to switch languages based on the current language context.

4. **Maintained Existing `index.html` Layout:**
   - Kept `index.html` unchanged, relying on partials to render content.

Despite these efforts, the site isn't generating the expected multilingual pages, and only certain partials are rendering.

---

### **`hugo.toml`**

```toml
## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Pedro Henrique P. Braga"
copyright = "{year}"

## -----------------------------------------------
## Language
## -----------------------------------------------

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[Languages]
  [Languages.en]
    languageName = "Canadian English"
    languageCode = "en-CA"
    weight = 1
  
  [Languages.fr]
    languageName = "Français (Canada)"
    languageCode = "fr-CA"
    weight = 2

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

# Personal parameters followed.
```

---

## **File Structure**

```
├── archetypes
├── assets
├── config
│   ├── _default
│   │   └── hugo.yaml
│   ├── development
│   │   └── hugo.toml
│   └── production
│       └── hugo.toml
├── content
│   └── post
│       ├── 2020-12-01-r-rmarkdown
│       │   ├── index.md
│       │   ├── index.Rmd
│       │   └── index_files
│             └── figure-html
│                 └── pie-1.png
├── data
│   ├── en
│   │   ├── banner.yml
│   │   ├── education.yml
│   │   ├── gallery.yml
│   │   ├── items.yml
│   │   ├── spotlight1.yml
│   │   ├── spotlight2.yml
│   │   └── spotlight3.yml
│   └── fr
│       ├── banner.yml
│       ├── education.yml
│       ├── gallery.yml
│       ├── items.yml
│       ├── spotlight1.yml
│       ├── spotlight2.yml
│       └── spotlight3.yml
├── index.Rmd
├── layouts
│   ├── _default
│   │   └── baseof.html
│   ├── index.html
│   ├── partials
│   │   ├── banner.html
│   │   ├── elements.html
│   │   ├── elements_reference.html
│   │   ├── favicon.html
│   │   ├── footer.html
│   │   ├── gallery.html
│   │   ├── head.html
│   │   ├── item.html
│   │   ├── items.html
│   │   ├── modifiers.html
│   │   ├── picture.html
│   │   ├── scripts.html
│   │   ├── spotlight-01-left.html
│   │   ├── spotlight-02-right.html
│   │   ├── spotlight-03-left.html
│   │   └── spotlight.html
│   └── shortcodes
│       └── blogdown
│           └── postref.html
├── netlify.toml
├── public
├── R
├── resources
├── static
│   └── images
├── themes
│   └── hugo-story
└── website-makeover.Rproj
```

---

### **`layouts/index.html`**

```html
{{ define "main" }}

    {{ partial "banner" site.Data.banner }}
    {{ partial "spotlight" site.Data.spotlight1 }}
    {{ partial "spotlight" site.Data.education }}
    {{ partial "spotlight" site.Data.spotlight3 }}
    {{ partial "spotlight" site.Data.spotlight2 }}
    {{ partial "items" site.Data.items }}
    {{ partial "elements" . }}
    {{ partial "elements_reference" . }}
    {{ partial "gallery" site.Data.gallery }}
    {{ partial "footer" . }}

{{ end }}
```

### **`layouts/partials/banner.html`**

```html
<!-- Banner -->
<section class="banner {{ .style }}">
    <div class="content">
        {{ with .title }}<h1>{{ . }}</h1>{{ end }}
        {{ with .subtitle }}<p class="major">{{ . | safeHTML }}</p>{{ end }}
        {{ with .content }}<p>{{ . | safeHTML }}</p>{{ end }}
        {{ with .social }}<ul class="icons">
            <li>
              <a target="_blank" href="{{ .github }}" class="icon brands style1 fa-github"><span class="label">Github</span></a>
              <a target="_blank" href="{{ .orcid }}" class="icon brandsai style1 ai-orcid"><span class="label">ORCiD</span></a>
              <a target="_blank" href="{{ .linkedin }}" class="icon brands style1 fa-linkedin"><span class="label">LinkedIn</span></a>
              <a target="_blank" href="mailto:{{ .email }}" class="fav icon style1 fa-envelope"><span class="label">Email</span></a>
              <a target="_blank" href="{{ .googlescholar }}" class="icon brandsai style1 ai-google-scholar"><span class="label">Google Scholar</span></a>
            </li>
        </ul>{{ end }}        
        {{ with .button }}<ul class="actions stacked">
  <li>
    <!-- The first link is the original button from your YAML data -->
    <a href="{{ .link }}" class="button primary large wide smooth-scroll">{{ .label }}</a>

    <!-- The second link forcibly points to the alternate language home. -->
    {{ if eq $.Site.Language.Lang "en" }}
      {{ with $.Site.Home.Translations.ByLang "fr" }}
        <a href="{{ .Permalink }}" class="button large">En français</a>
      {{ end }}
    {{ else }}
      {{ with $.Site.Home.Translations.ByLang "en" }}
        <a href="{{ .Permalink }}" class="button large">English</a>
      {{ end }}
    {{ end }}
  </li>
</ul>{{ end }}
    </div>  
    {{ with .image }}<div class="image">
        <img src="{{.}}" alt="Hugo Story" />
    </div>{{end}}
</section>
```

---

## **Observed Behavior**

- **Language Switch Issue:** Clicking on "En français" does not switch to the French version but instead scrolls the page down.
- **Partial Rendering:** Only certain elements (e.g., `elements` partial) are displaying on the homepage. Other partials like `banner`, `spotlight`, etc., are not rendering as expected.
- **Generated Pages:** Only the default language (English) seems to be generating correctly. French pages (`/fr/`) are not being created or are incomplete.

---

## **Expected Behavior**

- **Language Switching:** Clicking on "En français" should navigate to the French version of the site (`/fr/`), and vice versa.
- **Complete Rendering:** All partials (`banner`, `spotlight`, `items`, etc.) should render correctly for both English and French versions, pulling data from their respective `data/en/` and `data/fr/` YAML files.
- **Generated Pages:** Both `/en/` and `/fr/` homepages should be generated with complete content as defined by the partials and data files.
